---
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        type: choice
        description: Debug mode
        required: false
        options:
          - "true"
          - "false"
      lorem-ipsum:
        type: choice
        description: Lorem ipsum
        required: true
        options:
          - foo
          - bar
        default: foo

# Allow one concurrent
concurrency:
  group: ${{ format('{0}-{1}-{2}-{3}-{4}', github.workflow, github.event_name, github.ref, github.base_ref, github.head_ref) }}
  cancel-in-progress: true

env:
  DEBUG: ${{ inputs.debug || secrets.ACTIONS_RUNNER_DEBUG || vars.ACTIONS_RUNNER_DEBUG || secrets.ACTIONS_STEP_DEBUG || vars.ACTIONS_STEP_DEBUG || false }}
  FOO: BAR

jobs:
  validate:
    name: Validate
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            gh-workflows:
              - '.github/workflows/**'
            md:
              - '**/*.md'

      - name: actionlint
        if: ${{ steps.changes.outputs.gh-workflows == 'true' }}
        uses: raven-actions/actionlint@v1
        with:
          flags: "-ignore SC2086"

      - name: Markdown Links
        if: ${{ steps.changes.outputs.md == 'true' }}
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/linters/.markdown-link-check.json

      # - name: TruffleHog
      #   uses: trufflesecurity/trufflehog@main
      #   with:
      #     path: ./
      #     base: ${{ github.event.repository.default_branch }}
      #     head: HEAD
      #     extra_args: --debug --only-verified

      # - name: Run pre-commit
      #   run: |
      #     pip install pre-commit
      #     pre-commit run --all-files --verbose

  dog-food:
    name: Dog food (test inputs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dump Contexts Action (inputs)
        id: dump-contexts
        uses: ./
        with:
          vars-context: ${{ toJson(vars) }}
          secrets-context: ${{ toJson(secrets) }}
          needs-context: ${{ toJson(needs) }}
          inputs-context: ${{ toJson(inputs) }}
          smee: true

      - name: Dump Contexts outputs
        if: ${{ steps.dump-contexts.outputs.smee == 'true' }}
        run: |
          echo "Your SMEE.io URL is: ${{ steps.dump-contexts.outputs.smee-url }}"

      - name: Dump Contexts Action (no inputs)
        uses: ./

      - name: Dump Contexts Action (only debug)
        if: ${{ env.DEBUG == 'true' }}
        uses: ./
        with:
          vars-context: ${{ toJson(vars) }}
          secrets-context: ${{ toJson(secrets) }}
          needs-context: ${{ toJson(needs) }}
          inputs-context: ${{ toJson(inputs) }}

  dog-food-matrix:
    name: Dog food (test runners)
    needs:
      - dog-food
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dump Contexts Action
        uses: ./
        with:
          vars-context: ${{ toJson(vars) }}
          secrets-context: ${{ toJson(secrets) }}
          needs-context: ${{ toJson(needs) }}
          inputs-context: ${{ toJson(inputs) }}
